spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/starwars
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  cache:
    type: caffeine
    cache-names: peopleList, peopleDetail, peopleSearch
    caffeine:
      spec: maximumSize=500,expireAfterWrite=30m

  logging:
    level:
      org.springframework.cache: DEBUG
      com.github.benmanes.caffeine: DEBUG


